services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: learn-fast-with-ai
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # env_file:
    #   - ../.env
    volumes:
      # Mount the built .next directory from your local filesystem
      - ../.next:/app/.next
      # Mount public directory
      - ../public:/app/public
      # Mount the database directory for data persistence
      - ../data:/app/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

