version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: learn-fast-with-ai
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - ../.env
    volumes:
      # Mount source code for hot-reload in development
      - ../src:/app/src
      - ../public:/app/public
      - ../next.config.ts:/app/next.config.ts
      - ../tailwind.config.ts:/app/tailwind.config.ts
      - ../tsconfig.json:/app/tsconfig.json
      # Mount node_modules as volume to persist dependencies
      - node_modules:/app/node_modules
      # Mount database directory
      - ../data:/app/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge

